#!/bin/bash
# -*- coding: utf-8 -*-
#
# Resolve all dependencies that the application requires.

set -eo pipefail


function main () {
    cd "$(dirname "$0")/.."

    local python_exec="$(which python3)"
    local venv_exec="$(which virtualenv)"

    if [[ -n "${python_exec}" ]]; then
        echo "Using Python executable: ${python_exec}"

        if [[ -d .env ]]; then
            echo "ERROR: Virtual environment already exists: .env" >&2
            return 2
        fi

        if [[ -z "${venv_exec}" ]]; then
            pip install virtualenv
        fi
        echo "Using Virtualenv executable: ${venv_exec}"

        "${venv_exec}" -p "${python_exec}" .env
        source .env/bin/activate
        pip install -U setuptools wheel pip
        STATIC_DEPS=true LIBXML2_VERSION=2.9.2 pip install -r requirements.txt

        echo "Bootstrapping is done. To start using getwide activate the" \
            "virtual environment by typing:"
        echo "$ source .env/bin/activate"
        echo "$ python getwide.py --help"
    else
        echo "ERROR: Python executable not found. Interpreter version 3.5+" \
            "required" >&2
        return 1
    fi

    cd - > /dev/null
}


main "$@"
unset -f main
